version: "3.0"
services:
  redis:
    container_name: redis
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - loi
    ports:
      - "6379:6379"
networks:
  loi:
    driver: bridge
